package fr.sdis83.remocra.mobile.utils

object GlobalConstants {
    const val CREATION_PEI_MOBILE_PARAM = "CREATION_PEI_MOBILE"
    const val CREATION_PEI_MOBILE_DROIT = "CREATION_PEI_MOBILE"
    const val CREATION_GESTIONNAIRE_MOBILE_DROIT = "CREATION_GESTIONNAIRE_MOBILE"

    /**
     * Pour la gestion des agents
     */
    const val GESTION_AGENT = "GESTION_AGENT"
    const val UTILISATEUR_CONNECTE_OBLIGATOIRE = "UTILISATEUR_CONNECTE_OBLIGATOIRE"
    const val UTILISATEUR_CONNECTE = "UTILISATEUR_CONNECTE"
    const val COMPOSANT_AGENT_ONLY = "COMPOSANT_AGENT_ONLY"
    const val VALEUR_PRECEDENTE = "VALEUR_PRECEDENTE"
}
