package fr.sdis83.remocra.mobile.utils

object GlobalConstants {
    const val CREATION_PEI_MOBILE_PARAM = "CREATION_PEI_MOBILE"
    const val CREATION_PEI_MOBILE_DROIT = "CREATION_PEI_MOBILE"
    const val CREATION_GESTIONNAIRE_MOBILE_DROIT = "CREATION_GESTIONNAIRE_MOBILE"
}
